### ISSUE TITLE
Needless Response.clone() calls

### ISSUE THREAD

**Issue by hmnd** [elbywan/wretch-middlewares#21]
I have noticed that both the `retry` and `dedupe` modules call `response.clone()`  at least once for each request, even when the body is not read. This can be harmful to performance in applications such as serverless functions (eg. [Cloudflare Workers](https://developers.cloudflare.com/workers/platform/changelog#7132021)), in situations where the body is never read or is streamed through in the function's response.

I would recommend to remove these `response.clone()` calls. Instead a disclaimer could be added in the documentation reminding the user that, if their `until` or `onRetry` function reads the response body, they should call `response.clone()`  themselves. I can create a PR with this changed, but wanted to get feedback on such a change first.

**Comment by elbywan** [comment]
Hi @hmnd,

First sorry for not replying earlier, I'm a bit busy these days.

> I would recommend to remove these response.clone() calls. Instead a disclaimer could be added in the documentation reminding the user that, if their until or onRetry function reads the response body, they should call response.clone() themselves.

I would take the opposite approach actually! Cloning the response will always work and is essential to allow the body to be read by multiple sources. But allowing the user to customize how to resolve the response (by checking the `Content-Length` header for instance and cloning only if appropriate) would be best in my opinion.

So I pushed a commit to add a `resolver: Response => Response` option to both middlewares that allows the user to do exactly that. *(default is `response => response.clone()`*

**Comment by hmnd** [comment]
@elbywan Thanks so much for taking the time to consider this! I think that's a perfect solution :)
